# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~

    # your filter sets are defined here
    filter_sets:

        # use the default cache configuration
        cache: ~

        # the name of the "filter set"
        my_thumb:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 90], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background: { size: [124, 94], position: center, color: '#000000' }


        # name our first filter set "my_ratio_down_scale_filter"
        my_ratio_down_scale_filter:
            filters:

                # use and setup the "scale" filter
                scale:

                    # given 1920x1600px -> output 960x800px (relative down-scale)
                    to: 0.5

        # name our first filter set "my_ratio_up_scale_filter"
        my_ratio_up_scale_filter:
            filters:

                # use and setup the "scale" filter
                scale:

                    # given 1920x1600px -> output 5760x3200px (relative up-scale)
                    to: 2

        # name our third filter set "my_dim_down_scale_filter"
        my_dim_down_scale_filter:
            filters:

                # use and setup the "scale" filter
                scale:

                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 800, 1000 ]

        # name our fourth filter set "my_dim_up_scale_filter"
        my_dim_up_scale_filter:
            filters:

                # use and setup the "scale" filter
                scale:

                    # input 300x900px -> output 900x2700px (relative up-scale)
                    dim: [ 1200, 2700 ]


        card_scale_filter:
            filters:
                # use and setup the "scale" filter
                scale:

                    # input 1200x1600px -> output 750x1000px (relative down-scale)
                    dim: [ 830, 600 ]

        # name our fourth filter set "my_dim_up_scale_filter"
        small_upscale_filter:
            filters:

                # use and setup the "scale" filter
                scale:

                    # input 300x900px -> output 900x2700px (relative up-scale)
                    dim: [ 400, 600 ]

        small:
            filters:
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [250, 250]

                    # crop the input image, if required
                    mode: outbound


        bigger:
            filters:
                relative_resize:
                    widen: 750
