twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.root_dir%/../src/Extensions/Portfolio/templates': damnPortfolio
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
