CREATE TABLE tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE parameter (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, labels LONGTEXT NOT NULL COMMENT '(DC2Type:array)', parameters LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', template VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE fos_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, pa
ssword VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_957A647992FC23A8 (username_canonical), UN
IQUE INDEX UNIQ_957A6479A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_957A6479C05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE portrait (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, labels LONGTEXT NOT NULL COMMENT '(DC2Type:array)', descriptions LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', online TINYINT(1) NOT NULL, file VARCHAR(255) NOT NULL, slug VA
RCHAR(255) NOT NULL, updated DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE portrait_tag (portrait_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_4CFB5A5D1226EBF3 (portrait_id), INDEX IDX_4CFB5A5DBAD26311 (tag_id), PRIMARY KEY(portrait_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE publication (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, labels LONGTEXT NOT NULL COMMENT '(DC2Type:array)', descriptions LONGTEXT NOT NULL COMMENT '(DC2Type:array)', cover_image VARCHAR(255) DEFAULT NULL, online TINYINT(1) NOT NUL
L, slug VARCHAR(255) NOT NULL, updated DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE publication_tag (publication_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_20D75B4C38B217A7 (publication_id), INDEX IDX_20D75B4CBAD26311 (tag_id), PRIMARY KEY(publication_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGI
NE = InnoDB;
     CREATE TABLE serie (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, labels LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', online TINYINT(1) NOT NULL, slug VARCHAR(255) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, images LONGTEXT DEFAULT N
ULL COMMENT '(DC2Type:array)', descriptions LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', date_sent DATETIME NOT NULL, updated DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE serie_tag (serie_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_DD5453A9D94388BD (serie_id), INDEX IDX_DD5453A9BAD26311 (tag_id), PRIMARY KEY(serie_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE son (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, labels LONGTEXT NOT NULL COMMENT '(DC2Type:array)', descriptions LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', slug VARCHAR(255) NOT NULL, link VARCHAR(555) NOT NULL, online TINYI
NT(1) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE son_tag (son_id INT NOT NULL, tag_id INT NOT NULL, INDEX IDX_F0EA100E65EFA242 (son_id), INDEX IDX_F0EA100EBAD26311 (tag_id), PRIMARY KEY(son_id, tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     ALTER TABLE portrait_tag ADD CONSTRAINT FK_4CFB5A5D1226EBF3 FOREIGN KEY (portrait_id) REFERENCES portrait (id) ON DELETE CASCADE;
     ALTER TABLE portrait_tag ADD CONSTRAINT FK_4CFB5A5DBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE;
     ALTER TABLE publication_tag ADD CONSTRAINT FK_20D75B4C38B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE;
     ALTER TABLE publication_tag ADD CONSTRAINT FK_20D75B4CBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE;
     ALTER TABLE serie_tag ADD CONSTRAINT FK_DD5453A9D94388BD FOREIGN KEY (serie_id) REFERENCES serie (id) ON DELETE CASCADE;
     ALTER TABLE serie_tag ADD CONSTRAINT FK_DD5453A9BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE;
     ALTER TABLE son_tag ADD CONSTRAINT FK_F0EA100E65EFA242 FOREIGN KEY (son_id) REFERENCES son (id) ON DELETE CASCADE;
     ALTER TABLE son_tag ADD CONSTRAINT FK_F0EA100EBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE;
